# Generated by Django 2.1.1 on 2018-09-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_dir', models.CharField(max_length=200, verbose_name='file')),
                ('summary', models.CharField(max_length=1000, verbose_name='Summary')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Topic')),
            ],
        ),
    ]
