# Generated by Django 2.1.1 on 2018-09-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_router'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Router',
            new_name='Presentations',
        ),
    ]
