# Generated by Django 2.1.1 on 2018-09-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_auto_20180924_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presentations',
            new_name='PresentationFile',
        ),
    ]
