# Generated by Django 2.1.1 on 2018-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_auto_20180924_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='name',
            field=models.CharField(default='Draft', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='topics',
            field=models.CharField(default='Web Dev', max_length=200, verbose_name='Topics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentationfile',
            name='name',
            field=models.CharField(default='Draft', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file_dir',
            field=models.CharField(max_length=200, verbose_name='File'),
        ),
    ]
