# Generated by Django 2.1.1 on 2018-10-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0006_auto_20180927_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationfile',
            name='pres',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='file_dir',
        ),
        migrations.AddField(
            model_name='presentation',
            name='f',
            field=models.FileField(default='', upload_to='ppts/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PresentationFile',
        ),
    ]
