# Generated by Django 2.1.1 on 2018-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_auto_20181005_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
            ],
        ),
    ]
