# Generated by Django 2.1.1 on 2018-10-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_outreach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('bio', models.CharField(max_length=1000, verbose_name='Biography')),
            ],
        ),
        migrations.CreateModel(
            name='PersonOutreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.Outreach')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.Person')),
            ],
        ),
    ]
