# Generated by Django 2.1.1 on 2018-10-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0009_person_personoutreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='name',
            field=models.CharField(default='math magic', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
