# Generated by Django 2.1.1 on 2018-10-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0010_outreach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='level',
            field=models.CharField(default='', max_length=200, verbose_name='Level'),
            preserve_default=False,
        ),
    ]
