# Generated by Django 2.1.1 on 2018-10-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0012_auto_20181019_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personoutreach',
            name='outreach',
        ),
        migrations.RemoveField(
            model_name='personoutreach',
            name='person',
        ),
        migrations.RemoveField(
            model_name='presentationtopic',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='presentationtopic',
            name='topic',
        ),
    ]
