# Generated by Django 2.1.1 on 2018-10-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0013_auto_20181019_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='personoutreach',
            name='outreach',
            field=models.ForeignKey(default='Brown University', on_delete=django.db.models.deletion.CASCADE, to='coop.Outreach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personoutreach',
            name='person',
            field=models.ForeignKey(default='Thomas', on_delete=django.db.models.deletion.CASCADE, to='coop.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentationtopic',
            name='presentation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='coop.Presentation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentationtopic',
            name='topic',
            field=models.ForeignKey(default='Infinity', on_delete=django.db.models.deletion.CASCADE, to='coop.Topic'),
            preserve_default=False,
        ),
    ]
