# Generated by Django 2.1.1 on 2018-10-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0014_auto_20181019_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(upload_to='ppts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='f',
        ),
        migrations.AddField(
            model_name='file',
            name='pres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.Presentation'),
        ),
    ]
