# Generated by Django 2.1.1 on 2018-12-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0016_auto_20181202_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
