# Generated by Django 2.1.1 on 2018-12-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0019_remove_file_pres'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coop.Presentation'),
            preserve_default=False,
        ),
    ]
