# Generated by Django 2.1.1 on 2018-12-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0020_file_pres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f',
            field=models.FileField(upload_to=''),
        ),
    ]
