# Generated by Django 2.2 on 2019-04-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0022_auto_20190424_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='topics',
        ),
        migrations.AddField(
            model_name='presentation',
            name='topics',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Topic'),
        ),
    ]
