# Generated by Django 2.2 on 2019-04-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0023_auto_20190424_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
