# Generated by Django 2.2 on 2019-04-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0024_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=75, null=True, verbose_name='Name'),
        ),
    ]
